### ISSUE TITLE
which version should i use?

### ISSUE THREAD

**Issue by songsh** [chenenyu/Router#10]
i android sdk is 24, gradle is 2.14.1,
which version should i use,

 classpath 'com.chenenyu.router:gradle-plugin:0.2.0',
has error.

**Comment by chenenyu** [comment]
gradle 3.3

`classpath 'com.chenenyu.router:gradle-plugin:latest.integration'`

**Comment by songsh** [comment]
跟greendao 有冲突，

Error:Execution failed for task ':app:greendao'.
> org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(Ljava/lang/Object;)J

把router 去了，greendao 就正常了。

**Comment by chenenyu** [comment]
Plz refer this [issue](https://github.com/greenrobot/greenDAO/issues/498), it's greendao's bug.
