### ISSUE TITLE
插件化的路由支持

### ISSUE THREAD

**Issue by inshyma** [chenenyu/Router#100]
你好，我想通过路由跳转到插件的一个Activity，可以么？如可以请给一个思路或 demo

**Comment by chenenyu** [comment]
理论上是可以的。Router支持自定义的匹配器，例如你可以自定义一个Matcher继承自`AbsImplicitMatcher`，然后重写相关方法，具体的实现代码要看插件化框架的实现方式而定。欢迎在issue里继续探讨。

**Comment by chenenyu** [comment]
请问是否已解决呢？
