### ISSUE TITLE
Transform的一点问题

### ISSUE THREAD

**Issue by taoszu** [chenenyu/Router#107]
你好，我想问一下，在Transform中Scopes为SCOPE_FULL_PROJECT的时候，如果插件在library被引入，我这边会报错Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects. 很好奇你的插件为什么不会报错。

**Comment by chenenyu** [comment]
因为只在application module的时候才会插入Transform

**Comment by taoszu** [comment]
谢谢啦，之前看了你的库写的代码，百思不解，原来是看漏了。
