### ISSUE TITLE
关于http or https的路由支持

### ISSUE THREAD

**Issue by jaaksi** [chenenyu/Router#108]
banner的点击跳转，如果是http或者https的话，就跳转本地webActivity，给WebActivity添加路由http&https,但是不支持。改路由是否支持仅scheme匹配。如果不支持，那么像之中路由如果直接是http or Https的，怎么用这个框架支持。

**Comment by chenenyu** [comment]
可以支持。自定义一个`Matcher`，然后插入到Registry中就可以了，可以参考[wiki](https://github.com/chenenyu/Router/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%A3%E6%9E%90%E8%A7%84%E5%88%99)，如果有疑问，欢迎加群探讨
