### ISSUE TITLE
compiler.jar does not exit

### ISSUE THREAD

**Issue by hanouba** [chenenyu/Router#109]
编译运行的时候报错  改怎么解决

**Comment by chenenyu** [comment]
贴上完整log看下，还有使用的版本

**Comment by hanouba** [comment]
我是直接下载下来的，gradle改为gradle:3.1.3'  kotlin_version改成1.2.0了 buildToolsVersion改了27.0.3 其他的都没改 编译就卡在这里
Error:Transform output file G:\demo\aboutRouter\Router-master\compiler\build\libs\compiler.jar does not exist.
