### ISSUE TITLE
无法生成RouterBuildConfig类

### ISSUE THREAD

**Issue by WylAndy** [chenenyu/Router#11]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.chenenyu.router:gradle-plugin:latest.integration'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.chenenyu.router'

配置完成后rebuild不能生成RouterBuildConfig类，而且不支持Instant Run

**Comment by chenenyu** [comment]
至少要有一个注解，是不是没有使用注解就build了？

**Comment by WylAndy** [comment]
找到原因了，是主module里没加
