### ISSUE TITLE
with传递ArrayList <? extends Serializable>

### ISSUE THREAD

**Issue by snailflying** [chenenyu/Router#116]

**Comment by snailflying** [comment]
具体见AbsRouter.java内如下代码，
`else if (value instanceof ArrayList) {
            if (!((ArrayList) value).isEmpty()) {
                Object obj = ((ArrayList) value).get(0);
                if (obj instanceof Integer) {
                    bundle.putIntegerArrayList(key, (ArrayList<Integer>) value);
                } else if (obj instanceof String) {
                    bundle.putStringArrayList(key, (ArrayList<String>) value);
                } else if (obj instanceof CharSequence) {
                    bundle.putCharSequenceArrayList(key, (ArrayList<CharSequence>) value);
                } else if (obj instanceof Parcelable) {
                    bundle.putParcelableArrayList(key, (ArrayList<? extends Parcelable>) value);
                }
            }
        } `
此处没有做相应判断，导致ArrayList<? extends Serializable>不能传递。实际上ArrayList实现了Serializable，是可以通过Serializable来传递的。
说实话with()用起来确实方便，但是没有做强类型判断。可能会导致这种较为隐蔽的bug

**Comment by chenenyu** [comment]
感谢反馈 👍 我找个时间修复
