### ISSUE TITLE
这版本 52 是什么意思

### ISSUE THREAD

**Issue by 594238813** [chenenyu/Router#118]
com/chenenyu/router/compiler/processor/RouteProcessor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by chenenyu** [comment]
我这边用的jdk11，没有做兼容处理。。。 今天会重新发一个兼容jdk8的版本，抱歉

**Comment by 594238813** [comment]
麻烦快些   谢谢

**Comment by chenenyu** [comment]
试试1.6.2  如果没问题，也请反馈下。

**Comment by 594238813** [comment]
ok没问题 了
