### ISSUE TITLE
AppInterceptorsHandler拦截器优先级是否应该大于IntentProcessor等拦截器？

### ISSUE THREAD

**Issue by snailflying** [chenenyu/Router#122]
我在自定义拦截器内，修改Chain的Request值，比如首先赋值
chain.getRequest().getExtras().putString("showId", "123");
然后chain.process();
但是在跳转过去的目标页面是拿不到"showId"这个值的。因为Itent在IntentProcessor内赋值的。

**Comment by chenenyu** [comment]
谢谢反馈，目前的顺序的确不能赋值，欢迎提交PR

**Comment by snailflying** [comment]
加了一个拦截器，我给你提交个PR
