### ISSUE TITLE
获取fragment问题

### ISSUE THREAD

**Issue by wbbltx** [chenenyu/Router#125]
我在根module中，获取各个子module中的fragment，使用(Fragment) Router.build(url).getFragment(context)，但是获取不到，请问有可能是什么原因？

**Comment by chenenyu** [comment]
估计配置有问题？  先参照下demo的配置检查下

**Comment by wbbltx** [comment]
每个module中 apply plugin: 'com.chenenyu.router';
在fragment上头注解@Route(***);
最后 Router.build(url).getFragment(context)；
就是这些吧，我看demo中也没有别的配置了，

**Comment by chenenyu** [comment]
demo跑起来是没问题的吧？

**Comment by wbbltx** [comment]
是的，demo没问题，我用的是1.6.2。
另外也出现了java.lang.NoClassDefFoundError: com.chenenyu.router.apt.UserRouteTable 的问题，该module已经删掉了apply plugin: 'com.chenenyu.router'  仍然会有这个问题...哭了

**Comment by chenenyu** [comment]
`NoClassDefFoundError `这个问题已经在dev分支修了  这周会发个新版本。
