### ISSUE TITLE
问一下 这能在 lib里面用吗？

### ISSUE THREAD

**Issue by 594238813** [chenenyu/Router#128]

**Comment by 594238813** [comment]
我在lib里     的 applicaiton  初始化    
然后        Router.build(url).with(bundle).go(ctx);    这一行 断点也到了  就是没跳转

**Comment by chenenyu** [comment]
可以的   但是application module必须也配置上依赖

**Comment by 594238813** [comment]
Router.injectParams(this);    //配置在 activity里面了 
    implementation 'com.chenenyu.router:gradle-plugin:1.6.2'
@Route("webView")
![image](https://user-images.githubusercontent.com/14051142/58695631-71f39f00-83c8-11e9-90fb-6579471922af.png)
断电也到这里了  还是打不开页面  还可能是什么情况

**Comment by chenenyu** [comment]
不是这么配置的   
![image](https://user-images.githubusercontent.com/6647088/58697485-34911080-83cc-11e9-9aa0-f5e1102e38af.png)
建议参考下 demo的配置
