### ISSUE TITLE
1.6.3的拉取不到插件

### ISSUE THREAD

**Issue by cjk035** [chenenyu/Router#129]
![image](https://user-images.githubusercontent.com/5079841/59025016-c776f280-8885-11e9-967e-0d8fa5f08d19.png)

**Comment by chenqizheng** [comment]
确认下，rootProject的build.gradle文件中,是否指定了版本为"x.y.z"。
```groovy
ext {
    routerVersion = 'x.y.z'
    compilerVersion = 'x.y.z'
}
```
如果不指定特定版本，可以不用以上配置

**Comment by chenenyu** [comment]
你是不是指定了router的版本号...  没有 x.y.z 这个版本号
