### ISSUE TITLE
1.6.3版本更新后，运行时会出现通过pathString找不到fragment的问题

### ISSUE THREAD

**Issue by q876625596** [chenenyu/Router#131]
Router.build(newTag).getFragment(this)这个方法有时候会找不到fragment，然后我删除build文件夹之后重新编译就又可以了

**Comment by chenenyu** [comment]
是必现的吗？  以前用的什么版本，会不会出现这个问题？

**Comment by q876625596** [comment]
> 是必现的吗？ 以前用的什么版本，会不会出现这个问题？

不是必现的，大概编译10来次有那么一两次会出现，以前用的1.6.2没有出现过这个情况

**Comment by chenenyu** [comment]
Instant Run 是打开还是关闭状态

**Comment by q876625596** [comment]
> Instant Run 是打开还是关闭状态

打开的

**Comment by q876625596** [comment]
我现在切换回1.6.2用了几天也没这个问题

**Comment by chenenyu** [comment]
@chenqizheng 有没有可能是上次加的`WaitableExecutor `引起的

**Comment by chenqizheng** [comment]
@q876625596 请问下出问题的时候是只有部分路由无法找到吗？还是全部？Instant Run关闭的时候会出现吗？

**Comment by q876625596** [comment]
> @q876625596 请问下出问题的时候是只有部分路由无法找到吗？还是全部？Instant Run关闭的时候会出现吗？
我首页有4个tab，有时候就是其中一两个的Fragment找不到，没有关闭Instant Run试过。

**Comment by chenqizheng** [comment]
> > @q876625596 请问下出问题的时候是只有部分路由无法找到吗？还是全部？Instant Run关闭的时候会出现吗？
> > 我首页有4个tab，有时候就是其中一两个的Fragment找不到，没有关闭Instant Run试过。

出问题的时候在你AppRouteTable能看到这个Fragment的路由配置吗？我开Instant Run试了几十次没出现。编译十几次期间有改动出问题的Fragment代码吗？

**Comment by q876625596** [comment]
> > > @q876625596 请问下出问题的时候是只有部分路由无法找到吗？还是全部？Instant Run关闭的时候会出现吗？
> > > 我首页有4个tab，有时候就是其中一两个的Fragment找不到，没有关闭Instant Run试过。
> 
> 出问题的时候在你AppRouteTable能看到这个Fragment的路由配置吗？我开Instant Run试了几十次没出现。编译十几次期间有改动出问题的Fragment代码吗？

AppRouteTable我没注意，这个我得之后改到1.6.3版后复现问题再确认，我在编译期间有改动过出问题fragment

**Comment by chenqizheng** [comment]
出问题的Fragment是在单独的Module吗？

**Comment by q876625596** [comment]
对，4个Fragment都在不同的Module

**Comment by chenqizheng** [comment]
@chenenyu @q876625596   修改好了

原因是因为开启instant run后，有可能导致某些module的RouteTable没被Scanner收集到，上版本修改支持多Application Module直接把Records清空了。

修改成了通过Map缓存所有Application的Records。详情见：[这里](https://github.com/chenenyu/Router/commit/50bfc7c666bdcd36a70200518c003851e4ed738b)

**Comment by chenenyu** [comment]
`1.6.4` released.
