### ISSUE TITLE
router 1.6.3~1.6.4增量编译问题

### ISSUE THREAD

**Issue by fisherblue** [chenenyu/Router#133]
AGP:3.4.1
JAVA8
Gradle: 5.4.1

更新1.6.3（1.6.4也同样有问题）后，增量编译会报duplicate class，开始认为是google AGP的问题，所以提了一笔issue给google：https://issuetracker.google.com/issues/135628755#comment6
根据google工程师的分析，问题出在Router处理增量编译的逻辑上。

这个问题在1.6.2上也会出现，不过出现的概率明显小于1.6.3之后的版本。
麻烦看下这问题哦

**Comment by chenqizheng** [comment]
我看Route Transform是isIncremental是false，请问下1.6.3出现概率，大概多少次会出现一次。

**Comment by fisherblue** [comment]
修改一些关联比较多的class几乎必现。
只要修改了然后运行就会报错，然后必须rebuild然后重新运行才行

**Comment by chenqizheng** [comment]
的确有增量编译的问题，1.6.3~1.6.4增加了并发编译支持，导致问题更加的容易出现。

在dev分支提交了，增加了增量编译的支持。[修改详情点击这里](https://github.com/chenenyu/Router/commit/166f0da7f001027e6244f4c85b25bcb8cbb436c8)

PS：增删module、aar可能会有问题。没想好怎么去对应删除Scanner的Records。增删module、aar还是需要clean build才能正常。

**Comment by chenenyu** [comment]
@chenqizheng 可以先提到1.6分支上看看  1.7目前支持了androidx

**Comment by chenqizheng** [comment]
@chenenyu 好的，已经cherry-pick到了1.6。我试了增量编译十几次，没出现报错了。

**Comment by fisherblue** [comment]
@chenenyu @chenqizheng 准备好了的话可以发个小版本让我测试一下

**Comment by chenenyu** [comment]
@fisherblue 1.6.5-beta1 试试

**Comment by fisherblue** [comment]
@chenenyu 测试过了，问题没有出现了
