### ISSUE TITLE
混淆规则该怎么写呢😢

### ISSUE THREAD

**Issue by zhentou1993** [chenenyu/Router#136]

**Comment by chenenyu** [comment]
demo里有的

**Comment by zhentou1993** [comment]
谢谢，找到了🤣




------------------ 原始邮件 ------------------
发件人: "chenenyu"<notifications@github.com>; 
发送时间: 2019年8月27日(星期二) 晚上7:56
收件人: "chenenyu/Router"<Router@noreply.github.com>; 
抄送: "枕霞旧友"<424571227@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [chenenyu/Router] 混淆规则该怎么写呢&#x1F622; (#136)




demo里有的
