### ISSUE TITLE
androidx.fragment.app.Fragment

### ISSUE THREAD

**Issue by Arthurshen98** [chenenyu/Router#139]
错误: 无法访问Fragment
找不到androidx.fragment.app.Fragment的类文件

**Comment by Arthurshen98** [comment]
api 29
![image](https://user-images.githubusercontent.com/15273559/68743538-a7fea580-062d-11ea-8a8d-a7b3a64c1620.png)

你这里面全是androidx可是我不想支持androidx

**Comment by Arthurshen98** [comment]
没有把是否支持androidX的版本区分出来，所以用不了，支持androidx所有地方都报错

**Comment by chenqizheng** [comment]
请问下版本号是多少？

**Comment by chenqizheng** [comment]
如果不想升AndroidX，可以使用1.6.3的版本
