### ISSUE TITLE
请教，新版本看到 router 不需要初始化了，是怎么实现的呢？

### ISSUE THREAD

**Issue by gdutxiaoxu** [chenenyu/Router#140]
请教，新版本看到 router 不需要初始化了，是怎么实现的，目前看代码了解到会自动生成   AppRouteTable，但是在代码中查找，并没有发现调用 `handle(Map<String, Class<?>> map) ` 方法，请问是怎样实现的，很好奇

**Comment by chenqizheng** [comment]
router是用AOP技术，在编译期把路由表注入到静态代码块中。所以不需要手动初始化了。可以反编译看下AptHub。
