### ISSUE TITLE
Kotlin 项目中使用kts构建 plugin无法自动添加 kapt dependency

### ISSUE THREAD

**Issue by JasonHezz** [chenenyu/Router#143]
kts 部分代码如下
```
plugins {
    id("com.chenenyu.router")
    kotlin("android")
    kotlin("android.extensions")
    kotlin("kapt")
}
```
无法生成原因：
![image](https://user-images.githubusercontent.com/15358765/80752818-c8c8a200-8b5e-11ea-972e-f96e021164fa.png)
添加id实际上为 `org.jetbrains.kotlin.android`

plugin 代码
https://github.com/chenenyu/Router/blob/0a023b9fd8bee3285adc89bf496cbec212d858af/gradle-plugin/src/main/groovy/com/chenenyu/router/RouterPlugin.groovy#L50

可以看到plugin是依据 kotlin-android 添加 kapt compiler

临时解决方案：
```
dependencies {
    kapt("com.chenenyu.router:compiler:1.7.2")
}
```

**Comment by chenenyu** [comment]
感谢反馈，我看下

**Comment by chenenyu** [comment]
Try `1.7.3`.

**Comment by JasonHezz** [comment]
还是不能添加 晚上回家再Debug一下
