### ISSUE TITLE
Gradle 增加配置开关可以关闭日志输出

### ISSUE THREAD

**Issue by JasonHezz** [chenenyu/Router#146]
https://github.com/chenenyu/Router/blob/0a3a25277cbe368062746a8a186552410b5c5de5/compiler/src/main/java/com/chenenyu/router/compiler/util/Logger.java#L20

控制台输出信息过多 有时候难以查找关键信息

**Comment by chenenyu** [comment]
```groovy
ext {
    compilerLoggable = false
}
```
