### ISSUE TITLE
在未使用router的lib中apply plugin: 'com.chenenyu.router'，导致找不到uri

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#15]
#8 现象与这个issue类似。
我在base library和app application都应用了Router `apply plugin: 'com.chenenyu.router'`
但是在base中未实际使用router，导致在app中使用的时候报错：`Router: Can not find an Activity that matches the given uri: uriname`

log信息如下：
`I/Router: com.chenenyu.router.BaseRouteTable
I/RouteTable: {}
I/Router: There is no interceptor table in module: base.
I/InterceptorTable: {}
I/Router: There are no interceptors in module: base.
I/Router: There are no interceptors in module: app.
I/Interceptors: {}`

解决方法:不使用就不应用Router `apply plugin: 'com.chenenyu.router'`，在base中删除了就正常工作了

**Comment by chenenyu** [comment]
Fixed in new release v1.0.0, thanks.

**Comment by zhangchaoxu** [comment]
thanks
换成 classpath 'com.chenenyu.router:gradle-plugin:0.6.0'
发现Router.openLog();不见了

**Comment by chenenyu** [comment]
log的选项放到init接口里了，也可以使用`setDebuggable`开启
