### ISSUE TITLE
注解处理器生成类正常，AptHub路由表为空，RouterTransform没有找到AptHub

### ISSUE THREAD

**Issue by caihuanjian** [chenenyu/Router#150]
在编译日志有看到router: register target file not found.

**Comment by caihuanjian** [comment]
> 在编译日志有看到router: register target file not found.

项目里apply了很多plugin，把router这个插件放到apply plugin: 'com.android.application' 下边就可以了，apply router放到最后就不行，why。。。

**Comment by chenenyu** [comment]
可能被别的插件影响到了，你现在都apply了哪些插件？

**Comment by caihuanjian** [comment]
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.fordeal.router'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'io.fabric'
apply plugin: 'bugly'
apply plugin: 'com.huawei.agconnect'

**Comment by chenenyu** [comment]
用的是什么版本的
