### ISSUE TITLE
当某个Activity在Picture in Picture模式下时，通过router跳转的Activity会抢占Picture in Picture

### ISSUE THREAD

**Issue by xiaochilun** [chenenyu/Router#151]
当某个Activity在Picture in Picture模式下时，通过router跳转的Activity会抢占Picture in Picture。
但如果不使用router使用以下代码就正常；
val i = Intent()
 i.setClass(it, RActivity::class.java)
 startActivity(i)

**Comment by chenenyu** [comment]
我还没用过pip模式...  能否录个屏看看

**Comment by xiaochilun** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chenenyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上7:13
收件人:&nbsp;"chenenyu/Router"<Router@noreply.github.com&gt;;
抄送:&nbsp;"张雨民"<1436241312@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chenenyu/Router] 当某个Activity在Picture in Picture模式下时，通过router跳转的Activity会抢占Picture in Picture (#151)





 
我还没用过pip模式...  能否录个屏看看

**Comment by xiaochilun** [comment]
> 我还没用过pip模式... 能否录个屏看看

视频怎么样才可以发给您看

**Comment by chenenyu** [comment]
直接拖到这个评论的对话框里  就能上传

**Comment by xiaochilun** [comment]
![PIP_20200628214504](https://user-images.githubusercontent.com/12453685/85964929-c9aa7280-b9ed-11ea-9bcd-630180c5fd49.gif)

**Comment by xiaochilun** [comment]
跳转到观看历史页面使用的是Intent方式，跳转到离线缓存使用的router，gif图最后一帧可以看到离线缓存页面将画中画抢占了。

**Comment by chenenyu** [comment]
```kotlin
val i = Intent()
i.setClass(it, RActivity::class.java)
startActivity(i)
```
这段代码是在哪调用的？  使用Router时传入的context是首页的context吗？

**Comment by xiaochilun** [comment]
> ```kotlin
> val i = Intent()
> i.setClass(it, RActivity::class.java)
> startActivity(i)
> ```
> 
> 这段代码是在哪调用的？ 使用Router时传入的context是首页的context吗？

>代码是在跳转历史记录页面调用的；
>使用router传入的是Application实例；
刚刚将传入的context改成首页的context还是会出现抢占的情况

**Comment by chenenyu** [comment]
把调用的context改成同一个有问题吗？

**Comment by xiaochilun** [comment]
调用的context改成同一个(getActivity())还是会有问题

**Comment by xiaochilun** [comment]
大概发现了一些东西；

**Comment by xiaochilun** [comment]
发现了一些规律，
待跳转的Activity启动模式不是singleTask并且Router使用的context是Activity对象就不会出现抢占的现象了。

**Comment by chenenyu** [comment]
https://github.com/chenenyu/Router/blob/4ebfbd5a8c8626e7ee6eba773e16998c5b80be1b/router/src/main/java/com/chenenyu/router/RealRouter.java#L88-L98

Router跳转代码就这
