### ISSUE TITLE
关于跳转插件

### ISSUE THREAD

**Issue by 5peak2me** [chenenyu/Router#152]
首先感谢辛苦劳动，是个设计很nice的库，我这边基于当前路由库做了了下AS的跳转插件支持。方便查找定义和调用处。是否支持PR
![router1](https://user-images.githubusercontent.com/6847158/91542104-e876a800-e94f-11ea-8f43-05e6ee0afb74.gif)
- 初始版本
     - support AS 3.5+
     - support @Route navigation
     - support @Route(interceptors = "AInterceptor") navigation
     - support @Interceptor navigation
     - support Router navigation

- 下版本计划
    - 支持动态路由 handleTable 参数
    - 支持 addInterceptors 和 skipInterceptors 参数

**这边先整理下，后面提到dev分支**

**Comment by chenenyu** [comment]
欢迎PR！:smile:  可以把as插件的地址发下看看效果，或者提到dev分支

**Comment by 5peak2me** [comment]
> 欢迎PR！😄 可以把as插件的地址发下看看效果，或者提到dev分支
好的，我稍后fork下工程
