### ISSUE TITLE
UncaughtException detected: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/chenenyu/router/apt/TestRouteTable;

### ISSUE THREAD

**Issue by wchao1241** [chenenyu/Router#153]
TestModule 移除之后 
使用gradle打包后
一直报UncaughtException detected: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/chenenyu/router/apt/TestRouteTable;
IDE clean & restart 都不好用

**Comment by chenenyu** [comment]
手动删除build目录呢？
