### ISSUE TITLE
[Router 1.7.5]每次构建路由表都会发生变化，导致编译速度变慢

### ISSUE THREAD

**Issue by fisherblue** [chenenyu/Router#157]
![image](https://user-images.githubusercontent.com/11733093/102486146-90e97d00-40a3-11eb-8724-e93f306012ca.png)
![image](https://user-images.githubusercontent.com/11733093/102486189-9e9f0280-40a3-11eb-9411-1c92b6dd2d4f.png)
![image](https://user-images.githubusercontent.com/11733093/102486226-a9f22e00-40a3-11eb-8555-cf496d6c3cb2.png)
![image](https://user-images.githubusercontent.com/11733093/102486249-b37b9600-40a3-11eb-901c-b8c194f0decb.png)
![image](https://user-images.githubusercontent.com/11733093/102486265-bd04fe00-40a3-11eb-8bef-24be3e70a597.png)
AGP: 4.1.1
Gradle:6.5.1

**Comment by chenenyu** [comment]
这几天有点忙，可能过段时间才会看这个问题，如果你有时间，欢迎帮忙研究下~

**Comment by fisherblue** [comment]
好，先看看

**Comment by chenenyu** [comment]
试试`1.8.0`，有问题再联系
