### ISSUE TITLE
 1.7.5版本在release包中 mSettingFragment是null

### ISSUE THREAD

**Issue by vson1718** [chenenyu/Router#163]
@Route(AppRouterName.SET_SETTING_FRAGMENT)
public class SettingFragment extends BaseMvvmFragment<SetFragmentSettingBinding, SettingViewModel>{
}
 //1.7.5版本在release包中 mSettingFragment是null
 mSettingFragment = Router.build(AppRouterName.SET_SETTING_FRAGMENT).getFragment(this);

**Comment by chenenyu** [comment]
debug包没问题吗？

**Comment by vson1718** [comment]
问题解决了，debug和release模式切换的时候，产生的垃圾文件没有被清理
