### ISSUE TITLE
部分Module 不生效

### ISSUE THREAD

**Issue by aiLvXuan** [chenenyu/Router#166]
不知道各位使用过程中有没有遇到个别Module不生效的情况，Activity 跳转无反应。
以前跳转无效的时候，Rebuild 一下项目就可以了，后来Rebuild也不行了，替换 Router 版本，再Rebuild就可以了，后来换Router版本都不行了，再后来发现app打Release版本又可以，现在无论如何都不行了，短时间内想要撤掉Router，还真是有点麻烦，历史原因，已经超过了 500个 Router 跳转。

目前环境：
Router 1.7.6

Android Studio Arctic Fox | 2020.3.1
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 11 - 22000.132

gradle: gradle-5.6.2-all
gradle-tools: 3.5.4

android_compileSdkVersion = 29
android_buildToolsVersion = '29.0.2'
android_minSdkVersion = 22
android_targetSdkVersion = 30

**Comment by chenenyu** [comment]
请问编译过程中router生成的中间文件是正常的吗？在`build/generated/source/`下

**Comment by aiLvXuan** [comment]
在相应的 Module 的 build/generated/source/ 下面，只有 buildConfig 和 Butterknife 的 R2, 并没有生成 Router 的文件，build 过程中，打开了 router的日志，也并没有对应module的日志
@chenenyu

**Comment by chenenyu** [comment]
说明该module并没有注册成功，请问在module里面有`apply plugin: 'com.chenenyu.router'`吗？ 类似https://github.com/chenenyu/Router/blob/master/Sample/module1/build.gradle

**Comment by aiLvXuan** [comment]
> 请问编译过程中router生成的中间文件是正常的吗？在`build/generated/source/`下

但是在另一个目录，是有文件的，但我不确定这是否正常
![image](https://user-images.githubusercontent.com/22241686/129688089-2805724c-8797-4a32-be16-1bf267468689.png)

**Comment by aiLvXuan** [comment]
> > 请问编译过程中router生成的中间文件是正常的吗？在`build/generated/source/`下
> 
> 但是在另一个目录，是有文件的，但我不确定这是否正常
> ![image](https://user-images.githubusercontent.com/22241686/129688089-2805724c-8797-4a32-be16-1bf267468689.png)
这看起来是 Butterknife 生成的，并非是 Router， 我的 Module 有引用了Router 插件
![image](https://user-images.githubusercontent.com/22241686/129688667-41b1ee38-86af-4c8c-a217-a2d0dd632965.png)

**Comment by chenenyu** [comment]
`ModulePerson`看起来没问题，也生成了对应的`ModulePersonRouteTable`，这个module不能正常跳转吗？

**Comment by aiLvXuan** [comment]
> `ModulePerson`看起来没问题，也生成了对应的`ModulePersonRouteTable`，这个module不能正常跳转吗？

是的，看起来正常，但是不能跳转，在这个模块的Activity都不能跳转，而且并没有改动过代码，偶尔会出现Rebuild之后用不了，现在是不管怎么Rebuild都用不了了，该清理的缓存都清理了

**Comment by chenenyu** [comment]
如果方便的话，能不能帮忙构建一个最小体积的demo(不包含业务代码)，我来排查下

**Comment by aiLvXuan** [comment]
> 如果方便的话，能不能帮忙构建一个最小体积的demo(不包含业务代码)，我来排查下

嗯，有时间我尝试下，但是我也怀疑是我们项目太过于庞大，很多依赖库和插件导致了Router不能正常使用，而且，在这之前都是偶尔用不了，随着项目越来越庞大，情况越来越糟糕，单独去构建一个demo，我想不一定会触发这个bug

**Comment by chenenyu** [comment]
期待你的反馈，我也很好奇是什么原因导致的

**Comment by chenenyu** [comment]
试下`1.8.0`，换了一种初始化方式  @aiLvXuan
