### ISSUE TITLE
版本1.8.0，如果module的application为光秃秃的<application>。则报错org.xml.sax.SAXParseException; lineNumber: xxx; columnNumber: xxx; The prefix "android" for attribute "android:name" associated with an element type "meta-data" is not bound.

### ISSUE THREAD

**Issue by snailflying** [chenenyu/Router#168]
如题：
版本：1.8.0，
现象：
如果module的application为光秃秃的<application>。则报错org.xml.sax.SAXParseException; lineNumber: xxx; columnNumber: xxx; The prefix "android" for attribute "android:name" associated with an element type "meta-data" is not bound.

暂时规避方法：
将
```
<application>
xxx
</application>
```
改为：
```
<application
android:label="@string/app_name">
xxx
</application>
```

**Comment by chenenyu** [comment]
好的，我找时间看下。

**Comment by chenenyu** [comment]
请问module的清单文件里是否有这个属性：
`<manifest xmlns:android="http://schemas.android.com/apk/res/android" ...>`

**Comment by snailflying** [comment]
有的。唯一出问题的地方就是我上面描述的地方。原先是光秃秃的<application>，我随便加上个android:label=""属性就好了。

**Comment by chenyue404** [comment]
我的加了也不行
