### ISSUE TITLE
有时候跳转没反应。请问是什么原因呢。1.7.6

### ISSUE THREAD

**Issue by twlk-jzy** [chenenyu/Router#169]
有时候跳转没反应。请问是什么原因呢。1.7.6

**Comment by chenenyu** [comment]
必现还是偶先？ 试试1.8.0呢

**Comment by twlk-jzy** [comment]
> 必现还是偶先？ 试试1.8.0呢

偶尔出现   出现后。换其他版本 再换回来。又可以了。1.8.0  加上  报标签需要闭合 /

**Comment by chenenyu** [comment]
麻烦把1.8.0的log发给我，谢谢

**Comment by twlk-jzy** [comment]
'Element type "uses-sdk" must be followed by either attribute specifications, ">" or "/>".'

**Comment by twlk-jzy** [comment]
> 麻烦把1.8.0的log发给我，谢谢

'Element type "uses-sdk" must be followed by either attribute specifications, ">" or "/>".'

**Comment by chenenyu** [comment]
你的清单文件是什么样的

**Comment by twlk-jzy** [comment]
> 你的清单文件是什么样的

就是普通的清单文件。app。还有其他modules.  换成1.7.6版本就不会出这个问题

**Comment by chenenyu** [comment]
1.8.0优化了很多，麻烦贴一下app和module的manifest，我排查下问题，感谢

**Comment by twlk-jzy** [comment]
> 1.8.0优化了很多，麻烦贴一下app和module的manifest，我排查下问题，感谢

太多了。。。。。。

**Comment by twlk-jzy** [comment]
> 1.8.0优化了很多，麻烦贴一下app和module的manifest，我排查下问题，感谢

13个module。咋贴 。。

**Comment by chenenyu** [comment]
请问使用的gradle是什么版本的

**Comment by twlk-jzy** [comment]
> 请问使用的gradle是什么版本的

gradle-7.0.2-all.zip

classpath "com.android.tools.build:gradle:7.0.4"
