### ISSUE TITLE
'元素类型 "uses-sdk" 必须后跟属性规范 ">" 或 "/>"。'

### ISSUE THREAD

**Issue by Reign9201** [chenenyu/Router#171]
升级到 1.8.0之后，编译出现：
![image](https://user-images.githubusercontent.com/22032759/170435091-4329e230-7307-4860-8c39-cb5f81da1e0f.png)

**Comment by twlk-jzy** [comment]
我的也出现了。  回退了一个版本。才解决

**Comment by chenenyu** [comment]
能提供下清单文件的内容和使用的agp版本、gradle版本吗？

**Comment by chenenyu** [comment]
@artharyoung 感谢反馈，我看下，方便的话能提供一个能复现的最小demo吗？

**Comment by artharyoung** [comment]
> 

https://github.com/didi/DroidAssist/issues/38#issuecomment-1080378515

**Comment by chenenyu** [comment]
@artharyoung 1.8之前的版本使用了asm，1.8开始采用了无需修改字节码的方案，更优雅，我想要的是这个问题的demo： `编译也报类似错误：元素类型"manifest"必须后跟属性规范">"或"/>"`

**Comment by chenenyu** [comment]
已复现，正在解决

**Comment by chenenyu** [comment]
@Reign9201 @twlk-jzy @artharyoung 试试1.8.1版本

**Comment by hua060097** [comment]
请教下大佬，这个警告：Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable，是哪行代码解决的呢，这个出了有几千行的样子，好像是这个导致minifyReleaseWithR8速度超级慢，比原来的proguard还慢很多

**Comment by hua060097** [comment]
@chenenyu

**Comment by chenenyu** [comment]
什么版本？ @hua060097 贴下版本信息和日志吧

**Comment by hua060097** [comment]
AGP 7.2.2
gradle 7.3.3
抱歉，没有用这个Router，我是升级了Gradle7后，minifyReleaseWithR8 task的构建用了太多时间，一半时间在报“R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable. ”，搜索到了这里，看到您好像解决了这个警告，但是看commit，没能发现是哪一行代码解决了这个问题

**Comment by hua060097** [comment]
@chenenyu 我感觉可能是proguard文件里这个校验被R8忽略了，但是没有解决办法
<img width="279" alt="image" src="https://user-images.githubusercontent.com/7540771/210476109-bc409a07-6a1f-4f70-a878-72daee76b333.png">

**Comment by chenenyu** [comment]
之前使用了asm插桩，有这个警告，后来没用插桩就好了
