### ISSUE TITLE
fragment跳转fragment未生效?

### ISSUE THREAD

**Issue by wzc520pyfm** [chenenyu/Router#172]
fragment1:
@Route("test")
public class SetupFragment extends Fragment {....}

fragment2:
@Route("my")
public class MyFragment extends Fragment {
  ....
@OnClick(R.id.set_up)
    public void onClick(View v) {
        Toast.makeText(mContext, "点击了", Toast.LENGTH_SHORT).show(); // 可以正常执行
        Router.build("test").go(this); // 但这里没有成功跳转
    }
}
我跳转activity是可以成功跳转的, 但是fragment不行.
请帮帮我

**Comment by chenenyu** [comment]
fragment不能直接跳转，要先获取，然后自己用FragmentManager跳转

**Comment by wzc520pyfm** [comment]
懂了, 感谢
