### ISSUE TITLE
Cannot invoke method appendNode() on null object

### ISSUE THREAD

**Issue by Reign9201** [chenenyu/Router#176]
1.8.1版本新问题
![image](https://user-images.githubusercontent.com/22032759/177098005-b29ddfa4-237b-4c54-94ff-ca2ed2a34c9b.png)

gradle信息：
classpath "com.android.tools.build:gradle:7.0.3"
gradle版本 gradle-7.2-all.zip

**Comment by chenenyu** [comment]
方便贴下module里的清单文件吗？

**Comment by Reign9201** [comment]
对应报错的module，AndroidManifest文件里，是空的：
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.huami.sleep.data">

</manifest>
```

**Comment by chenenyu** [comment]
试过1.8.2版本没？

**Comment by Reign9201** [comment]
已换成1.8.2版本，这个版本没问题

**Comment by Reign9201** [comment]
不过，集成到1.8.2之后，出现下面的问题。。。
![image](https://user-images.githubusercontent.com/22032759/177292204-79b665e4-fea5-4885-9b69-5794ba7e582a.png)

**Comment by chenenyu** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/6647088/177309326-dba18c46-4f40-4016-b5aa-b1c2a11e6f06.png">
方便贴下module下的这两个文件吗

**Comment by Reign9201** [comment]
还没生成这两个文件就编译终止了
![image](https://user-images.githubusercontent.com/22032759/177441656-5bc12305-6aeb-4ac9-8565-ab9549208973.png)
复现步骤，一个module使用1.8.2生成aar包，然后集成到主工程，再编译就出现此问题了

**Comment by chenenyu** [comment]
你是先把把module生成aar，然后再集成到主工程吗？ 我还没测试过这种方式，依赖1.8.2生成aar的过程是ok的，然后编译主工程的时候报错了是吧？能看下aar里面的manifest吗？

**Comment by Reign9201** [comment]
![image](https://user-images.githubusercontent.com/22032759/177460154-eeaacbd5-5af7-4e39-bb79-2b413d4dee87.png)

**Comment by Reign9201** [comment]
![image](https://user-images.githubusercontent.com/22032759/177460339-3a6d2963-5291-42e6-9ae6-94f5255fffc2.png)

**Comment by chenenyu** [comment]
好的，我等下测试下这种使用场景

**Comment by Reign9201** [comment]
这里还有个问题，因为之前一直使用的是1.7.5版本，发现这个版本经常出现路由失效问题，断点发现这部分返回null了
![image](https://user-images.githubusercontent.com/22032759/177462904-eeef9fe7-58be-4ab2-9e31-d4881b3dd60e.png)
实际上路由表是存在的

**Comment by Reign9201** [comment]
尝试了module使用1.7.5版本，主工程使用1.8.0版本，没有出现上述报错了，但发现这两个版本是不兼容的，1.8.0以上版本看源码是通过下面方式注入的：
![image](https://user-images.githubusercontent.com/22032759/177478892-6360ddc5-7973-4917-8f6b-161ea41b739b.png)
但1.7.5版本在编译之后其实是没有生成meta-data的，导致module里面的路由表都不会被注入进去，不知道我这理解对不对

**Comment by chenenyu** [comment]
请试下`1.8.3-beta1`
