### ISSUE TITLE
建议: 加入changelog

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#26]
最近更新了0.8.0 0.8.1等等新版本
建议加入changelog，以便使用者决定是否升级使用新版本。

毕竟已经上线的应用，升级任意一个依赖都是有风险的。

Thanks

**Comment by chenenyu** [comment]
不错的建议，一般更新只会新增功能，极小的可能涉及到api变动，不会太影响原有的使用体验，大致的更新内容可见[Releasees页面](https://github.com/chenenyu/Router/releases)。
