### ISSUE TITLE
需要帮助:Interceptor中如何调用异步网络请求

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#27]
*需求*：在router打开一个新页面的时候需要用Interceptor做一下判断，比如判断是否已经登录(这个可以通过本地数据判断，可以实现)，也有可能需要判断用户身份(可能需要调用网络请求判断)。
请教一下，如何在Interceptor中调用异步的网络请求，然后根据网络返回数据来返回true/false实现跳转拦截与否的逻辑。

Thanks

**Comment by chenenyu** [comment]
这个最好在跳转之前判断，在网络返回之后做判断是否跳转；如果非要在Interceotor中做，只能先返回false，然后根据网络返回结果重新调用router

**Comment by zhangchaoxu** [comment]
收到，thanks

**Comment by chenenyu** [comment]
@zhangchaoxu 新版本已发布，小小的重构了一下`RouteInterceptor`接口，方便控制所有参数，当然不升级也没影响。
