### ISSUE TITLE
不支持Android Studio 3.0

### ISSUE THREAD

**Issue by TeemozZ** [chenenyu/Router#31]
使用com.android.tools.build:gradle:3.0.0-alpha1的情况下，注解似乎无效。例如@Route("test")，使用Router.build("test").go(context)时提示：Can not find an Activity that matches the given uri:test

**Comment by chenenyu** [comment]
具体是哪一块不支持？

**Comment by chenenyu** [comment]
目前`Android Gradle Plugin 3.0.0-alphaX`的版本还有不少bug，可以先使用2.2.x~2.3.x的版本

**Comment by chenenyu** [comment]
可以加qq群详聊，确定问题的原因。

**Comment by mars-ma** [comment]
警告: 来自注释处理程序 'com.chenenyu.router.compiler.processor.RouteProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'

貌似是因为AS 3.0只能使用1.8以上版本的JDK，所以注解这块有问题。

**Comment by ITDreamSKY** [comment]
同样的问题，请问你解决了吗？
@mars-ma 
PS:为什么给close了 = = 
@chenenyu

**Comment by chenenyu** [comment]
@ITDreamSKY 没问题啊   你可以加群详聊
