### ISSUE TITLE
v1.2.1中使用Interceptor有什么要求

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#36]
原先的Interceptor使用方式，在v1.2.1中，代码没进入这个Interceptor。
请问是使用方式有什么变化吗？
`
@Route(value = "ProfileEdit", interceptors = "Login")
public class ProfileEditActivity extends Activity 
`

`
@Interceptor("Login")
public class LoginInterceptor implements RouteInterceptor
`

**Comment by chenenyu** [comment]
没有任何变化啊，你看看初始化的log

**Comment by chenenyu** [comment]
fixed in `1.2.2`.
