### ISSUE TITLE
有没有这种操作

### ISSUE THREAD

**Issue by CK875430315** [chenenyu/Router#40]
public interface RouterService {

    @FullUri("router://com.baronzhang.android.router.FourthActivity")
    void startUserActivity(@UriParam("cityName") 
            String cityName, @IntentExtrasParam("user") User user);
    
}
接下来我们就可以通过如下方式实现 Activity 的跳转传参了：

 RouterService routerService = new Router(this).create(RouterService.class);
 
 User user = new User("张三", 17, 165, 88);
 routerService.startUserActivity("上海", user);

**Comment by chenenyu** [comment]
你这种是借鉴Retrofit的思想吧，需要用动态代理来实现。假如存在多个互不依赖的module，那么RouterService的存放与创建就有问题了。而且并不比现有的方式简洁。

**Comment by CK875430315** [comment]
在需要跳转的activity里添加注解，注解的activity多了 都不知道哪些activity被注解，感觉不好同一管理，       // 动态添加路由
        Router.handleRouteTable(new RouteTable() {
            @Override
            public void handle(Map<String, Class<?>> map) {
                map.put("dynamic", DynamicActivity.class);
            }
        });
动态管理的话，如果上面的代码实在library里，DynamicActivity是主工程app的界面，那该如何引用DynamicActivity

**Comment by chenenyu** [comment]
为什么不把代码实现放在主app里呢，每个module都可以操作`handleRouteTable `，最后会合并到一起。

**Comment by CK875430315** [comment]
这是用到的一个第三方的库，把这个代码方法放到主app里，代码移植量非常大，这个是网易的IM。因为之前用到的是另外一个平台的的IM，就是跟你说的一样把代码和资源文件什么的都移到了主app工程里，搬进去的时候还好，但是换掉它的时候很痛苦，现在很难保证一直用网易的所以。。。。

**Comment by chenenyu** [comment]
你在每个module里都操作一次`Router.handleRouteTable`，分别把当前module的activity添加进去，这样就不用移植了

**Comment by CK875430315** [comment]
恩，是的，在每个module把需要对外提供的activity都先Router.handleRouteTable加进去
