### ISSUE TITLE
router path是否考虑支持自定义schema

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#41]
目前的router path是否可以支持自定义schema，并且获取到参数？

需求来源 是想在h5中打开app的，在h5中定义schema并且带参数，如myappschema://information/view?id=1234。
目前的处理办法是对于App的InformationViewActivity增加过滤

`<intent-filter>
 <action android:name="android.intent.action.VIEW"/>
 <category android:name="android.intent.category.DEFAULT"/>
 <category android:name="android.intent.category.BROWSABLE"/>
 <data android:scheme="myappschema"/>
</intent-filter>`

然后在activity初始化的时候获取到id值
`Uri uri = getIntent().getData();
String id = uri.getQueryParameter("id");`

********

请教一下是否可以使用router来简化这部分工作？

**Comment by chenenyu** [comment]
h5打开app，这个动作是由系统发起的，并不经过Router，所以`<intent-filter>`是一定要配置的，据我所知这可能是唯一的方式了。当然你可以添加一个中转Activity，在这个Activity中获取scheme后面携带的path和query，然后利用Router进行分发，调起真正的目标页面。

**Comment by zhangchaoxu** [comment]
嗯，为了更加通用，尝试加入中转activity。
Thanks

ps. 话说这h5打开app也是个坑啊，微信内置浏览器、qq浏览器、百度浏览器都有白名单吧，自定义schema都有可能会被拦截。

`public class SchemaFilterActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Uri uri = getIntent().getData();
        Router.build(uri).go(this);
        finish();
    }

}`
