### ISSUE TITLE
跳转web url失败

### ISSUE THREAD

**Issue by YinST** [chenenyu/Router#45]
跳转https://m.baidu.com  会使用BrowserMatcher匹配器匹配，AbsImplicitMatcher  generate生成intent时，会校验@Nullable Class<?> target是否是activity，如果给fragment添加route注解后,可能传进来的是fragment导致跳转失败，
for (Map.Entry<String, Class<?>> entry : entries) {
                    if (matcher.match(context, mRouteRequest.getUri(), entry.getKey(), mRouteRequest)) {
                        RLog.i("Caught by " + matcher.getClass().getCanonicalName());
                        // Ignore implicit intent.
                        if (!(matcher instanceof AbsImplicitMatcher) &&
                                intercept(context, entry.getValue())) {
                            return null;
                        }
                        Object intent = matcher.generate(context, mRouteRequest.getUri(), entry.getValue());
                        if (intent instanceof Intent) {
                            assembleIntent((Intent) intent);
                            return (Intent) intent;
                        }
                        return null;
                    }
                }
matcher.generate时直接传进了路由表中的class,路由表中的class有可能是fragment

**Comment by chenenyu** [comment]
谢谢反馈，我先看下代码。

**Comment by chenenyu** [comment]
fragment相关的代码，核心在`RealRouter#getFragment(context)`这个方法，你可以看下，里面过滤掉了`AbsImplicitMatcher `。

**Comment by YinST** [comment]
Router.build(“https://m.baidu.com”).go(this);   调用go的时候会调用   RealRouter#getIntent(context)  方法 ，这个方法里面也会编译路由表，路由表里面有fragment

**Comment by chenenyu** [comment]
```
Object intent = matcher.generate(context, mRouteRequest.getUri(), entry.getValue());
if (intent instanceof Intent) {
    assembleIntent((Intent) intent);
    return (Intent) intent;
}
return null;
```
`getIntent(context)`中会做类型检查，如果匹配上了`fragment`的路由，生成的就不是`intent`了，而是`fragment`对象，会返回null。

**Comment by chenenyu** [comment]
你可以把你失败的示例代码贴上来，具体分析下。

**Comment by chenenyu** [comment]
Reopen it if you have any other questions.
