### ISSUE TITLE
建议在Router.build可以自由指定拦截器的添加和跳过

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#46]
1. 建议在跳转的时候加入拦截器添加Router.build(uri).addInterceptors(String... interceptors)，原因是有些activity可能只在某些特定的场景下才需要拦截器。

2. 建议在 Router.build(url).skipInterceptors(String... interceptors)可以带参，制定跳过的拦截器，原因是在某些时候，我只需要跳过某个拦截器，另外的几个拦截器任然是需要的。

加入以上两个特性，可以更加灵活的使用拦截器。

Thanks

**Comment by chenenyu** [comment]
考虑中，谢谢反馈。

**Comment by chenenyu** [comment]
`1.2.5`

**Comment by zhangchaoxu** [comment]
赞，试过skipInterceptors(String... )了，可以工作

**Comment by zhangchaoxu** [comment]
addInterceptors()逻辑上是没什么问题，不过引起另外一个问题GlobalInterceptor貌似过了两遍。

我在Application中 定义了Router.addGlobalInterceptor(new LoginInterceptor());在addInterceptors("TestInterceptor")后，实际调用的拦截器顺序是LoginInterceptor->TestInterceptor->LoginInterceptor,也就是说GlobalInterceptor过了两遍。

**Comment by chenenyu** [comment]
我这边测试没有什么问题 ，你看看是不是调用逻辑有点问题。
