### ISSUE TITLE
Does the lib support cross-module route?

### ISSUE THREAD

**Issue by Luolc** [chenenyu/Router#5]
The [wiki page](https://github.com/chenenyu/Router/wiki/路由框架的意义) writes that route framework is significant for modular develop. Thats correct but how to make cross-module route rule by this lib? I have had a lab but did not find out the way. Do I miss something?

**Comment by chenenyu** [comment]
如果是插件化的module，目前只能通过隐式intent跳转。

**Comment by Luolc** [comment]
@chenenyu Certainly, an explicit intent has no way to be used in a url-based route framework. But I thought the major point is how to simplify our work by the help of annotations, which is not supported yet if we are following modular develop. To be honest, I've been thinking about the designing of a cross-module route framework for some time and failed to find a solution without run-time level annotations. Feel free to have a discussion via whatever IM(WeChat etc.) if you are interested. :)

**Comment by chenenyu** [comment]
Yeah. My wechat is: chenenyu.
