### ISSUE TITLE
Demo无法跳转，提示Can not find an Activity that matches the given uri: module1

### ISSUE THREAD

**Issue by tokiii** [chenenyu/Router#50]
Demo都无法跳转，Demo直接down下来就可以了吧，还用配置啥么

**Comment by chenenyu** [comment]
不需要，你是手动改了什么配置么？ 可以进群交流一下。

**Comment by tokiii** [comment]
![image](https://user-images.githubusercontent.com/3972083/30267619-b8def136-9715-11e7-8cb6-04b335db3fff.png)

**Comment by tokiii** [comment]
就改了这一块

**Comment by tokiii** [comment]
![image](https://user-images.githubusercontent.com/3972083/30267700-f8a16eb6-9715-11e7-8a0a-dfc38ef59780.png)

**Comment by chenenyu** [comment]
我刚本地改成`2.3.3`测试也是没问题的，入群交流一下吧

**Comment by tokiii** [comment]
已加

**Comment by chenenyu** [comment]
I have released a new version of router-gradle-plugin(`1.2.5.1`) just now, it fixed this issue. Feel free to contact me if you have questions any more. 😆
