### ISSUE TITLE
Router无法跳转初始化失败

### ISSUE THREAD

**Issue by Mack-Hoo** [chenenyu/Router#51]
E/Router: Initialization failed, have you forgotten to apply plugin: 'com.chenenyu.router' in application module?

**Comment by Mack-Hoo** [comment]
使用  1.2.4，初始化就可以成功，可以实现跳转，1.2.5  版本就会出现Initialization failed, have you forgotten to apply plugin: 'com.chenenyu.router' in application module?

**Comment by hzyxym** [comment]
发现我的也会

**Comment by chenenyu** [comment]
@Mack-Hoo @hzyxym 我今天检查一下代码

**Comment by Mack-Hoo** [comment]
@chenenyu 谢谢了

**Comment by Mack-Hoo** [comment]
@chenenyu 好的

**Comment by chenenyu** [comment]
![image](https://user-images.githubusercontent.com/6647088/30304809-fa3c35ee-97a1-11e7-8c33-1034d4839a0d.png)
看看有没有生成这个文件，另外提供下gradle的版本

**Comment by Mack-Hoo** [comment]
gradle 2.3.3   
![8134ee5a-5604-4d4d-9add-62058c29ae08](https://user-images.githubusercontent.com/11731124/30305046-5a70a46c-97a3-11e7-8f11-44152becce60.png)

**Comment by Mack-Hoo** [comment]
@chenenyu  gradle 2.3.3  
![8134ee5a-5604-4d4d-9add-62058c29ae08](https://user-images.githubusercontent.com/11731124/30305102-a3aea098-97a3-11e7-91ae-4119fe33e371.png)

**Comment by chenenyu** [comment]
初步确定是升级了gradle版本导致的，可以将wrapper中的gradle版本提升到4.1试试，我后面会想办法兼容一下

**Comment by Mack-Hoo** [comment]
@chenenyu  wrapper中gradle版本提升到4.1试了还是不行

**Comment by chenenyu** [comment]
@Mack-Hoo try `1.2.5.1`

**Comment by hzyxym** [comment]
辛苦了，现在没问题了。
