### ISSUE TITLE
部分接口要求api等级过高

### ISSUE THREAD

**Issue by xxw8393** [chenenyu/Router#59]
`    @Override
    public void go(Context context) {
        Intent intent = getIntent(context);
        if (intent == null) {
            return;
        }

        Bundle options = mRouteRequest.getActivityOptionsCompat() == null ?
                null : mRouteRequest.getActivityOptionsCompat().toBundle();

        if (context instanceof Activity) {
            ActivityCompat.startActivityForResult((Activity) context, intent,
                    mRouteRequest.getRequestCode(), options);

            if (mRouteRequest.getEnterAnim() != 0 && mRouteRequest.getExitAnim() != 0) {
                // Add transition animation.
                ((Activity) context).overridePendingTransition(
                        mRouteRequest.getEnterAnim(), mRouteRequest.getExitAnim());
            }
        } else {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            ContextCompat.startActivity(context, intent, options);
        }
`

这里的   ContextCompat.startActivity(context, intent, options); 建议修改为
            if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                context.startActivity(intent, options);
            } else {
                context.startActivity(intent);
            }

**Comment by chenenyu** [comment]
`ContextCompat.startActivity(context, intent, options);` 这个api是support-v4：25.1.0版本开始加入的，请问你那边现在使用的v4是什么版本的呢？

**Comment by xxw8393** [comment]
24.2.1 感觉还是有不少人会用老版本的 建议兼容一下。。

**Comment by xxw8393** [comment]
对了 新的注册模块的方法感觉不如以前的方式啊.. 以前的app类可以不做修改了。 现在这样需要手工注册的话每次添加一个新的模块就需要修改一下app有些麻烦

**Comment by chenenyu** [comment]
好的，会跟你说的另一个问题一起改进，感谢反馈。

**Comment by chenenyu** [comment]
由于android gradle plugin 3.0包含了大量更新，很多以前的api都不可用了，导致以前的集成方式在3.0以后失效，所以被迫改成手动注册了。。。

**Comment by xxw8393** [comment]
可以在RouterProcesser里面生成一个模块管理类， 然后在app里用反射去调用这个管理类的方法实现注册

**Comment by chenenyu** [comment]
try `1.3.2`.
