### ISSUE TITLE
ProGuard config

### ISSUE THREAD

**Issue by Piasy** [chenenyu/Router#6]
As `RealRouter.java` uses reflection, we need add ProGuard config as below:

```
# Router
-keep class **RouteTable { *; }
-keep class <app package name>.BuildConfig { *; }
```

**Comment by chenenyu** [comment]
Yeah, i forgot it.

**Comment by shangwfa** [comment]
Class<?> buildConfig = Class.forName(packageName + ".BuildConfig");
            Field MODULES_NAME = buildConfig.getField("MODULES_NAME");
            String modules_name = (String) MODULES_NAME.get(buildConfig);
            String[] modules = modules_name.split(",");

这一部分代码是想读取BuildConfig类的MODULES_NAME数据，可是这个MODULES_NAME数据你是在哪里配置的？

**Comment by chenenyu** [comment]
@shangwfa gradle.
