### ISSUE TITLE
想了个办法用来自动生成modules并注册

### ISSUE THREAD

**Issue by xxw8393** [chenenyu/Router#62]
注册modules的地方从BuildConfig里读取：
Router.registerModules(new HashSet(Arrays.asList(BuildConfig.ALL_MODULES.split(","))));

BuildConfig里的字符串是在build.gradle里生成的
buildConfigField "String", "ALL_MODULES", "\"${getRouterModules()}\""

def getRouterModules() {
    StringBuilder sb = new StringBuilder()
    Set<Project> subs = project.rootProject.subprojects
    subs.findAll {
        it.plugins.hasPlugin("com.android.library") &&it.plugins.hasPlugin("com.chenyu.router") 
    }
    .each {
        sb.append(validateName(it.name)).append(",") // library
    }
//    sb.append(validateName(project.name)) // app
    return sb
}

**Comment by chenenyu** [comment]
subprojects.findAll 在3.0以后的脚本中不稳定，基本无效。

**Comment by xxw8393** [comment]
没有可替代接口啊?

**Comment by chenenyu** [comment]
有兴趣的话 可以checkout一份源码，切到1.2分支，然后测试
