### ISSUE TITLE
无法识别 路由咋回事 

### ISSUE THREAD

**Issue by xiejinsorry** [chenenyu/Router#64]
1. 初始化
     Router.initialize(new Configuration.Builder()
                .setDebuggable(BuildConfig.DEBUG)
                .registerModules("app", "easeui")
                .build());
2.给Acitivity 添加注解
@Route("cartondetail")
3.在一个工具类里面跳转
Intent intent = Router.build("cartondetail").getIntent(context);
                        intent.putExtra("feed_id", id);
                        context.startActivity(intent);
有什么问题吗？ 为什么找不到这个路由呢？

**Comment by chenenyu** [comment]
是否忘记在build.gradle中传入注解处理器的参数？  可以参考下demo的配置

**Comment by xiejinsorry** [comment]
两个地方都加了 一个在 依赖的lib 一个在 app 里面加了  javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["moduleName": project.name]
            }
        }

**Comment by xiejinsorry** [comment]
lib 名字叫 easeui  主工程module 名字就叫app 
Router.initialize(new Configuration.Builder()
.setDebuggable(BuildConfig.DEBUG)
.registerModules("app", "easeui")
.build());

**Comment by xiejinsorry** [comment]
studio 是  3.0  没有使用butterknife或者lambda

**Comment by xiejinsorry** [comment]
折腾你这 个 sdk 一下午了 还是不行

**Comment by xiejinsorry** [comment]
我这是什么情况？

**Comment by chenenyu** [comment]
编译过程和初始化过程都有log，我现在没法分析，可以加群贴上log看看

**Comment by xiejinsorry** [comment]
Can not find an Activity that matches the given uri: cartondetail 这是log

**Comment by xiejinsorry** [comment]
There is no InterceptorTable in module: app.
12-12 17:38:16.751 5689-5689/com.htgames.animesama I/Router: There is no InterceptorTable in module: easeui.

**Comment by LiuC520** [comment]
我知道啥问题了，我也遇到了同样的问题，你在settings.gradle中添加你的所有的module，include ':app', ':easeui'；然后还要在app的build.gradle中compile      compile project(':easeui')，然后应该就行了，我也是这个问题，解决了
