### ISSUE TITLE
[help wanted]在activity中注入的参数是否可以传递到fragment中

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#67]
目前打开一个新页面，新页面是activity套fragment的方式。
打开新activity通过with传递了三五个参数，而实际使用这些参数的是被嵌套的fragment。
现在我需要现在activity中@InjectParam这些参数,然后依次with到被嵌套的fragment。
最后再在fragment中@InjectParam这些参数。
实际新activity只是一个中间套，无需处理，只需要原样把参数传递就可以。

是否有更加合理的办法处理，直接将activity获取到的参数传递给fragment？

**Comment by chenenyu** [comment]
我暂时没想到其他方式，因为fragment接收参数貌似只有`setArguments`一种方式，在跳转Activity之前是不知道目标页面是否嵌套了fragment的，也不知道嵌套的是哪些fragment，所以只能自己处理了。

**Comment by zhangchaoxu** [comment]
ok, thanks
