### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by Hiram-Y** [chenenyu/Router#7]
有没有根据注解，自动生成 路由跳转的文档

**Comment by chenenyu** [comment]
什么意思？你是想查看注解和Activity的对应关系吗？

**Comment by Hiram-Y** [comment]
生成映射关系文档

**Comment by chenenyu** [comment]
这个倒是没有，毕竟生成的映射类也是很简洁明了的，如果你有什么好想法，欢迎一起讨论下 😆
