### ISSUE TITLE
[Feature] 支持 js 与 Native 互相通信?

### ISSUE THREAD

**Issue by Guang1234567** [chenenyu/Router#70]
Hello chenenyu:

能否支持 [JsUrlRouter](https://tech.hikyson.cn/2016/04/18/2016-4-18-%E3%80%90%E8%BD%AC%E3%80%91%E5%A5%BD%E5%A5%BD%E5%92%8Ch5%E6%B2%9F%E9%80%9A%EF%BC%81%E5%87%A0%E7%A7%8D%E5%B8%B8%E8%A7%81%E7%9A%84hybrid%E9%80%9A%E4%BF%A1%E6%96%B9%E5%BC%8F/#UrlRouter) ?  能否加入到您的 TODO-LIST 中去? 谢谢.

API maybe as below:

```java
OtherObject  otherObj = new OtherObject();

Router.build(uri).go(context/fragment/otherObj ) // 支持任意对象
```

```java
/**
* 一个既不是 Activity 也不是 Fragment 的类
*/
public class OtherObject extends Object {

	// 注解支持到方法级别
	@Route({"testOnCallFromJs001", "http://example.com/testOnCallFromJs001", "router://testOnCallFromJs001"}) 
	public void onCallFromJs001()
   {
		// dosth001
   }

	@Route({"testOnCallFromJs002", "http://example.com/testOnCallFromJs002", "router://testOnCallFromJs002"}) 
	public void onCallFromJs002()
   {
		// dosth001
   }
}

```

**Comment by chenenyu** [comment]
我先看一下这篇文章，评估下再回复你，感谢反馈。

**Comment by Guang1234567** [comment]
补充一下大概用法:

public class NavWebViewClient extends WebViewClient {
    private Context context;

    OtherObject  mHandlerJsCall = new OtherObject(); // 处理来自 js 的请求

    public NavWebViewClient(Context context){
        this.context = context;
    }
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        if(Router.build(uri).go(mHandlerJsCall))){
            return true;
        }
        view.loadUrl(url);
        return true;
    }
}

**Comment by chenenyu** [comment]
大概可以做，我忙完手里的活就开始开发，欢迎交流想法。

**Comment by Guang1234567** [comment]
Thank you.

**Comment by chenenyu** [comment]
@Guang1234567 预计下周一二会出个beta版，请问你下周可以参与早期试用吗？

**Comment by Guang1234567** [comment]
可以, 最近恶补了一下 annotationprocess 到时可以一起找 bug... ^_^

**Comment by chenenyu** [comment]
@Guang1234567 `1.4.0-beta1`  我今天把wiki补上

**Comment by Guang1234567** [comment]
@chenenyu 

好的, 另外为什么在 https://bintray.com/search?query=com.chenenyu.router 没找到您的库的?

您是发布在哪里的?

**Comment by chenenyu** [comment]
@Guang1234567 在`dev`分支上

**Comment by faith333** [comment]
个人觉得这个功能违背了router的初衷. 路由的目标做解耦, 用uri的协议实现调用方和目标对象的无关联. 然而这种场景既然已经引用到了目标类, 那何必不直接调用而要通过路由呢?

**Comment by chenenyu** [comment]
@faith333 你说的对，我最开始没做这个功能就是考虑到这一点。现在做了是作为一个孵化功能，优点可能就是省去了很多分支语句，并且集中管理，看看以后有没有更好的解决方案吧。

**Comment by Guang1234567** [comment]
针对 @faith333 所说: 

应该用 wiki 里的 https://github.com/chenenyu/Router/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B7%AF%E7%94%B1%E8%A1%A8 来解决.

```java

public class NavWebViewClient extends WebViewClient {
    private Context context;

    public NavWebViewClient(Context context){
        this.context = context;
    }
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        if(Router.build(uri).go())){  // <----  为了解耦, 这里的不能写成 .go(mHandlerJsCall), 这里只是单纯的把 uri 发送出去
            return true;
        }
        view.loadUrl(url);
        return true;
    }
}


// 伪代码请勿介意
void main() {

OtherObject  mHandlerJsCall = new OtherObject(); // 处理来自 js 的请求

// 动态添加路由表
Router.handleRouteTable(new RouteTable() {
    @Override
    public void handle(Map<String, Runnable> map) {  // <----  这里改成 Runnable or 别的?>
        map.put("http://www.mycompany.com/callSomeMethod", new Runnable() {
              @ovverride
              public void run() {
                    mHandlerJsCall.callSomeMethod();
               }
         });

        map.put("http://www.mycompany.com/startABCActivity", new Runnable() {
              @ovverride
              public void run() {
                    context.startActivity(new intent(context, startABCActivity.class))
               }
         });
    }
}); 

}
````

**Comment by chenenyu** [comment]
@Guang1234567 方法的路由不能过分解耦，这样容易造成混乱，大家都在自己的组件里定义路由方法，容易冲突。 
> 最后我想说的是: Github 上 所有的 router 库, 怎么感觉越用越像是 Eventbus, 只不过所谓的Event 变成了一个网址 ⊙﹏⊙|||  

本质都是事件分发，EventBus是纯粹的分发，特别简单，而Router针对跳转加了很多自己的功能(比如Matcher等)
