### ISSUE TITLE
针对插件化的路由方案

### ISSUE THREAD

**Issue by zhaoyubetter** [chenenyu/Router#73]
目前在插件方面有个问题 请教下，因为路由表里面存的 是activity 引用，对于插件 无法获取其activity 引用，相应的是类名全路径字符串了. 通过component 进行启动。请问这块有计划支持吗 目前我们准备采用变通方式 ，通过主工程 透明activity 进行中转

**Comment by chenenyu** [comment]
Router在设计的时候并没有考虑插件化，因为插件化的方案比较复杂。但是由于Router自身的灵活性，特别是`Matcher`的设计，使得支持插件化并不是没有可能，建议阅读一下wiki中关于匹配器的相关部分，尝试通过自定义Matcher来实现该功能。如果有其他问题，可以继续探讨。

**Comment by chenenyu** [comment]
先close了，如果还有问题，可以reopen
