### ISSUE TITLE
找不到activity

### ISSUE THREAD

**Issue by JeremyAiYt** [chenenyu/Router#8]
为什么我加了 注解  @Route("test")  使用router跳转时，callback返回找不到activity。
不是只添加注解就可以了吗？

**Comment by chenenyu** [comment]
是否忘记初始化了 `Router.initialize()` ？

**Comment by JeremyAiYt** [comment]
Router.initialize() 调过了啊，还有什么要注意的么

**Comment by chenenyu** [comment]
加群截图详聊吧，271849001

**Comment by zhangchaoxu** [comment]
我也遇到了类似问题，请问最后是如何解决的？
