### ISSUE TITLE
是否考虑将source version提高到jdk1.8

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#81]
升级了AS3.1
AS一直提醒warning: Supported source version 'RELEASE_7' from annotation processor 'com.chenenyu.router.compiler.processor.RouteProcessor' less than -source '1.8'
是否考虑将router的source version提高到1.8.

btw,这个warning不影响正常使用

**Comment by chenenyu** [comment]
预计还有少量开发者用的1.7，提高到1.8可能会影响他们的使用，以后看看情况再改吧
