### ISSUE TITLE
拦截器顺序(优先级)问题

### ISSUE THREAD

**Issue by zhangchaoxu** [chenenyu/Router#83]
请问拦截器有没有顺序(优先级)的。
我现在不管是通过注解加入interceptors = {"Ops","Login"}的，还是add加入的(addInterceptors("Login"))
一直都是先过其中的Ops，再过Login。
注解中也调整过前后顺序，也没有用。

请问如果我想指定拦截器的顺序，应该怎么设置？

**Comment by chenenyu** [comment]
目前拦截器没有考虑优先级的问题，而且内部是通过HashSet来维护的，不保证顺序，我近期解决下这个问题。

**Comment by zhangchaoxu** [comment]
好的，谢谢

**Comment by chenenyu** [comment]
`router: 1.4.2`

**Comment by zhangchaoxu** [comment]
赞速度
