### ISSUE TITLE
无法携带数据

### ISSUE THREAD

**Issue by cike** [chenenyu/Router#85]

**Comment by cike** [comment]
Router.buidd("xxxx").with("key1", "123").go(context). 我在目标activity中通过Router.build("xxx").getIntent() 然后在intent和bundle中查找数据根本找不到

**Comment by chenenyu** [comment]
数据不是这么接收的，直接在目标activity中的bundle中获取即可，可以看下demo.

邓冰 <notifications@github.com> 于 2018年5月29日周二 14:34写道：

**Comment by cike** [comment]
好谢谢

**Comment by chenenyu** [comment]
不客气，有问题可以随时反馈~
