### ISSUE TITLE
Interceptor中调用Router.build().getFragment() 导致AbsRouter 中的RouteRequest被修改

### ISSUE THREAD

**Issue by chenqizheng** [chenenyu/Router#86]
场景如下：

新增了 全局的 Interceptor
Router.addGlobalInterceptor(new FunctionActivityInterceptor());

在Interceptor中调用Router.build().getFragment()，导致了AbsRouter中的RouteRequest变成了getFragment的RouterRequest。
由于在Interceptor调用getFragment需要skipInterceptors（不然会出现递归死循环），若没有找到Fragment，没法设置不跳过Interceptor，因为Router.build()返回的是IRouter，只有skipInterceptors，没有不跳过Interceptor的设置。

FunctionActivityInterceptor代码如下：

```java
public class FunctionActivityInterceptor implements RouteInterceptor {
    @Override
    public boolean intercept(Context context, RouteRequest routeRequest) {
        Fragment fragment = (Fragment) Router.build(routeRequest.getUri()).with(routeRequest.getExtras()).skipInterceptors().getFragment(context);
        if (fragment != null) {
            return true;
        } else {
            return false;
        }
    }
}

```

**Comment by chenenyu** [comment]
请问使用的是什么版本？

**Comment by chenqizheng** [comment]
compile 'com.chenenyu.router:router:1.3.2'
annotationProcessor 'com.chenenyu.router:compiler:1.3.2'

**Comment by chenenyu** [comment]
更新到最新版本试试
