### ISSUE TITLE
RouteInterceptor 返回Object，每个拦截器都要写获取context的方法

### ISSUE THREAD

**Issue by gzsll** [chenenyu/Router#91]
Object返回的是Fragment或者Context，每个拦截器需要使用Context时都要做个判断Object类型，再获取~ 如何处理比较好？

**Comment by zhangchaoxu** [comment]
+1

**Comment by zhangchaoxu** [comment]
这个object是作者为了解决我的这个issue #76 引起的。
确实给intercept时候获取context造成了一点麻烦，我现在是instanceof做判断获取的

**Comment by chenenyu** [comment]
我有时间会想想如何重构下，大家有什么好的意见可以一起交流

**Comment by chenenyu** [comment]
@gzsll 试试1.5.0
