### ISSUE TITLE
Router和VirtualAPK不兼容？

### ISSUE THREAD

**Issue by hibernate3** [chenenyu/Router#96]
发现集成了VirtualAPK后，Route的跳转就不生效了。发现作者同为VirtualAPK的贡献者，请问知道什么原因吗？

**Comment by chenenyu** [comment]
具体的可以在群里提问，贴上详细信息。

**Comment by hibernate3** [comment]
只是在宿主同一个module内部跳转：
W/Router: Can not find an Activity that matches the given uri: family_manage
